programs:
    test:
        cmd: tail -f
        numprocs: 1
        umask: 022
        autostart: true
        autorestart: always
        exitcodes:
            - 0
            - 2
        startretries: 3
        startsecs: 5
        stopsignal: 34
        stopsecs: 10
        user: jlefonde
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
    test2:
        cmd: "cat"