taskmasterd:
    nodaemon: true
    nocleanup: false
    childlogdir: /var/log/taskmasterd/
    logfile: /var/log/taskmasterd/taskmasterd.log
    loglevel: error
programs:
    tail:
        cmd: tail -f
        numprocs: 2
        autostart: true
        autorestart: always
        exitcodes:
            - 0
            - 2
        startretries: 3
        startsecs: 5
        stopsignal: TERM
        stopsecs: 2
        user: jlefonde
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
        stderr_logfile: auto
    echo:
        cmd: echo "test"
        exitcodes: 1
        startsecs: 1
        autorestart: never
    test:
        cmd: /home/jlefonde/Documents/taskmaster/test
        stopsignal: USR1
        stopsecs: 2
        env:
            TEST: "123"