programs:
    nginx:
        cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
        numprocs: 1
        umask: 022
        workingdir: /tmp
        autostart: true
        autorestart: always
        exitcodes:
            - 0
            - 2
        startretries: 3
        startsecs: 5
        stopsignal: TERM
        stopsecs: 10
        stdout_logfile: /tmp/nginx.stdout
        stderr_logfile: /tmp/nginx.stderr
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
    nginx2:
        cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
        autorestart: "always"
    nginx3:
        cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
        autorestart: "never"
    nginx4:
        cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
        autorestart: on-failure

