taskmasterd:
    nocleanup: false
    childlogdir: /var/log/taskmasterd/
    logfile: /var/log/taskmasterd/taskmasterd.log
    loglevel: critical
programs:
    tail:
        cmd: tail -f
        numprocs: 2
        autostart: true
        autorestart: always
        exitcodes:
            - 0
            - 2
        startretries: 3
        startsecs: 5
        stopsignal: TERM
        stopsecs: 2
        user: jlefonde
        stderr_logfile: auto
    echo:
        cmd: echo "test"
        exitcodes: 1
        startsecs: 1
        autorestart: never
    test:
        cmd: /home/jlefonde/Documents/test
        umask: 007
        workingdir: /tmp
        stopsignal: USR2
        stopsecs: 2
        env:
            FILE_PATH: taskmasterd-test
        stderr_logfile: NONE
        stdout_logfile: ./test.log
