taskmasterd:
    nodaemon: true
    nocleanup: false
    childlogdir: ./
    logfile: /var/log/taskmasterd.log
    loglevel: error
programs:
    test:
        cmd: echo "Hello, World!"
        numprocs: 1
        umask: 022
        autostart: true
        autorestart: always
        exitcodes:
            - 0
            - 2
        startretries: 3
        startsecs: 5
        stopsignal: 34
        stopsecs: 10
        user: jlefonde
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
        stderr_logfile: none
    test2:
        cmd: "cat"
        stdout_logfile: none
        stderr_logfile: auto