programs:
    nginx:
        cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
        numprocs: 1
        umask: 022
        workingdir: /tmp
        autostart: true
        autorestart: always
        exitcodes:
            - 0
            - 2
        startretries: 3
        startsecs: 5
        stopsignal: TERM
        stopsecs: 10
        stdout_logfile: /tmp/nginx.stdout
        stderr_logfile: /tmp/nginx.stderr
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
    test1:
        cmd: "test1"
        autorestart: "always"
    test2:
        cmd: "test2"
        autorestart: "never"
    test3:
        cmd: "test3"
        autorestart: on-failure
    test4:
        cmd: "test4"
        autorestart: jsp

